# Generated by Django 6.0.6 on 2026-06-27 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research', '0001_initial'),
        ('startup_ideas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_type', models.CharField(choices=[('COMPETITOR', 'Competitor'), ('MARKET_SIZE', 'Market Size'), ('MARKET_TREND', 'Market Trend'), ('USER_PAIN_POINT', 'User Pain Point'), ('USER_DEMAND', 'User Demand'), ('TARGET_AUDIENCE', 'Target Audience'), ('PRICING', 'Pricing'), ('BUSINESS_MODEL', 'Business Model'), ('TECHNOLOGY', 'Technology'), ('REGULATION', 'Regulation'), ('FUNDING', 'Funding'), ('OPPORTUNITY', 'Opportunity'), ('RISK', 'Risk'), ('OTHER', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('normalized_title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('extractor_name', models.CharField(max_length=255)),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pending'), ('EXTRACTED', 'Extracted'), ('SKIPPED', 'Skipped'), ('FAILED', 'Failed')], default='PENDING', max_length=50)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('research_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='research.researchsource')),
                ('startup_idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='startup_ideas.startupidea')),
            ],
            options={
                'indexes': [models.Index(fields=['startup_idea'], name='knowledge_f_startup_bae988_idx'), models.Index(fields=['finding_type'], name='knowledge_f_finding_b10135_idx'), models.Index(fields=['processing_status'], name='knowledge_f_process_436734_idx'), models.Index(fields=['confidence_score'], name='knowledge_f_confide_c48e11_idx'), models.Index(fields=['created_at'], name='knowledge_f_created_963cf8_idx'), models.Index(fields=['normalized_title'], name='knowledge_f_normali_b01887_idx')],
                'constraints': [models.UniqueConstraint(fields=('research_source', 'finding_type', 'normalized_title'), name='unique_finding_per_source')],
            },
        ),
    ]
