# Generated by Django 6.0.6 on 2026-06-27 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_intelligence', '0001_initial'),
        ('startup_ideas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('MARKET', 'Market'), ('COMPETITION', 'Competition'), ('DEMAND', 'Demand'), ('BUSINESS_MODEL', 'Business Model'), ('REVENUE', 'Revenue'), ('TECHNOLOGY', 'Technology'), ('EXECUTION', 'Execution'), ('SCALABILITY', 'Scalability'), ('RISK', 'Risk')], max_length=50, unique=True)),
                ('weight', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('minimum_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('maximum_score', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('MARKET', 'Market'), ('COMPETITION', 'Competition'), ('DEMAND', 'Demand'), ('BUSINESS_MODEL', 'Business Model'), ('REVENUE', 'Revenue'), ('TECHNOLOGY', 'Technology'), ('EXECUTION', 'Execution'), ('SCALABILITY', 'Scalability'), ('RISK', 'Risk')], max_length=50)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade', models.CharField(max_length=20)),
                ('summary', models.TextField()),
                ('strengths', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('GENERATED', 'Generated'), ('SUPERSEDED', 'Superseded')], default='GENERATED', max_length=50)),
                ('version', models.PositiveIntegerField(default=1)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_from_insights', models.ManyToManyField(related_name='supported_assessments', to='business_intelligence.insight')),
                ('startup_idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_assessments', to='startup_ideas.startupidea')),
            ],
            options={
                'indexes': [models.Index(fields=['startup_idea'], name='assessment__startup_2f8f65_idx'), models.Index(fields=['assessment_type'], name='assessment__assessm_c00953_idx'), models.Index(fields=['status'], name='assessment__status_1ffc5e_idx'), models.Index(fields=['percentage'], name='assessment__percent_d05f79_idx'), models.Index(fields=['created_at'], name='assessment__created_8d828a_idx')],
                'constraints': [models.UniqueConstraint(fields=('startup_idea', 'assessment_type', 'version'), name='unique_assessment_version')],
            },
        ),
        migrations.CreateModel(
            name='OverallAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade', models.CharField(max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('summary', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('startup_idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overall_assessments', to='startup_ideas.startupidea')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('startup_idea', 'version'), name='unique_overall_version')],
            },
        ),
    ]
