# Generated by Django 6.0.6 on 2026-06-27 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recommendations', '0001_initial'),
        ('startup_ideas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUPERSEDED', 'Superseded'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=50)),
                ('summary', models.TextField(blank=True)),
                ('total_tasks', models.PositiveIntegerField(default=0)),
                ('completed_tasks', models.PositiveIntegerField(default=0)),
                ('blocked_tasks', models.PositiveIntegerField(default=0)),
                ('critical_tasks', models.PositiveIntegerField(default=0)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('overall_duration_days', models.PositiveIntegerField(default=0)),
                ('estimated_completion', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('startup_idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to='startup_ideas.startupidea')),
            ],
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('estimated_days', models.PositiveIntegerField(default=1)),
                ('default_priority', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('OPTIONAL', 'Optional')], default='MEDIUM', max_length=20)),
                ('default_phase', models.CharField(choices=[('IMMEDIATE', 'Immediate'), ('SHORT_TERM', 'Short Term'), ('MEDIUM_TERM', 'Medium Term'), ('LONG_TERM', 'Long Term')], default='MEDIUM_TERM', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('depends_on', models.ManyToManyField(blank=True, related_name='dependent_templates', to='roadmaps.tasktemplate')),
                ('recommendation_rule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_template', to='recommendations.recommendationrule')),
            ],
        ),
        migrations.CreateModel(
            name='RoadmapTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('IMMEDIATE', 'Immediate'), ('SHORT_TERM', 'Short Term'), ('MEDIUM_TERM', 'Medium Term'), ('LONG_TERM', 'Long Term')], max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('estimated_days', models.PositiveIntegerField(default=1)),
                ('priority', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('OPTIONAL', 'Optional')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('BLOCKED', 'Blocked')], default='PENDING', max_length=50)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dependencies', models.ManyToManyField(blank=True, related_name='dependent_tasks', to='roadmaps.roadmaptask')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_tasks', to='recommendations.recommendation')),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='roadmaps.roadmap')),
                ('task_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_tasks', to='roadmaps.tasktemplate')),
            ],
            options={
                'ordering': ['phase', 'order'],
            },
        ),
        migrations.AddConstraint(
            model_name='roadmap',
            constraint=models.UniqueConstraint(fields=('startup_idea', 'version'), name='unique_roadmap_version'),
        ),
        migrations.AddConstraint(
            model_name='tasktemplate',
            constraint=models.UniqueConstraint(fields=('recommendation_rule', 'title'), name='unique_task_template'),
        ),
        migrations.AddConstraint(
            model_name='roadmaptask',
            constraint=models.UniqueConstraint(fields=('roadmap', 'task_template'), name='unique_roadmap_task_template'),
        ),
    ]
