# Generated by Django 6.0.6 on 2026-06-27 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
        ('roadmaps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roadmaptask',
            options={'ordering': ['phase', 'dependency_level', 'execution_order']},
        ),
        migrations.RenameField(
            model_name='roadmaptask',
            old_name='order',
            new_name='dependency_level',
        ),
        migrations.AddField(
            model_name='roadmaptask',
            name='execution_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roadmaptask',
            name='recommendation_priority_snapshot',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='roadmaptask',
            name='recommendation_title_snapshot',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='roadmaptask',
            name='scheduled_end_day',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='roadmaptask',
            name='scheduled_start_day',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='roadmaptask',
            name='recommendation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_tasks', to='recommendations.recommendation'),
        ),
        migrations.CreateModel(
            name='RoadmapProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tasks', models.PositiveIntegerField(default=0)),
                ('completed_tasks', models.PositiveIntegerField(default=0)),
                ('blocked_tasks', models.PositiveIntegerField(default=0)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('remaining_days', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('roadmap', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='roadmaps.roadmap')),
            ],
        ),
    ]
