# Generated by Django 6.0.6 on 2026-06-27 08:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('startup_ideas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('industry', models.JSONField(default=list, help_text='List of preferred industries')),
                ('stage', models.JSONField(default=list, help_text='List of preferred funding stages')),
                ('country', models.JSONField(default=list, help_text='List of preferred countries/regions')),
                ('ticket_size_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ticket_size_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('risk_appetite', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='investors.investor')),
            ],
        ),
        migrations.CreateModel(
            name='StartupInvestorMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('compatibility_score', models.IntegerField(help_text='Match score from 0-100')),
                ('match_status', models.CharField(choices=[('SUGGESTED', 'Suggested'), ('CONTACTED', 'Contacted'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='SUGGESTED', max_length=20)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startup_matches', to='investors.investor')),
                ('startup_idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_matches', to='startup_ideas.startupidea')),
            ],
            options={
                'unique_together': {('startup_idea', 'investor')},
            },
        ),
        migrations.CreateModel(
            name='MatchExplanation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matched_industries', models.JSONField(default=list)),
                ('matched_stage', models.BooleanField(default=False)),
                ('matched_budget', models.BooleanField(default=False)),
                ('reasoning', models.TextField(help_text='Detailed explanation of the match rationale')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='explanation', to='investors.startupinvestormatch')),
            ],
        ),
    ]
