# Generated by Django 6.0.6 on 2026-06-27 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text="CSS class for icon, e.g., 'bi bi-heart'", max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Industries',
                'constraints': [models.UniqueConstraint(fields=('slug',), name='unique_industry_slug')],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('slug',), name='unique_tag_slug')],
            },
        ),
        migrations.CreateModel(
            name='StartupIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=200)),
                ('short_description', models.CharField(max_length=300)),
                ('problem_statement', models.TextField()),
                ('proposed_solution', models.TextField()),
                ('target_audience', models.TextField()),
                ('business_model', models.TextField(blank=True)),
                ('revenue_model', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('startup_stage', models.CharField(choices=[('IDEA', 'Idea'), ('VALIDATION', 'Validation'), ('MVP', 'MVP'), ('GROWTH', 'Growth')], default='IDEA', max_length=20)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('last_analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='startup_ideas', to='startup_ideas.industry')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startup_ideas', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='startup_ideas', to='startup_ideas.tag')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner'], name='startup_ide_owner_i_2b9a84_idx'), models.Index(fields=['status'], name='startup_ide_status_b02ce6_idx'), models.Index(fields=['industry'], name='startup_ide_industr_6874fb_idx'), models.Index(fields=['slug'], name='startup_ide_slug_6151a2_idx'), models.Index(fields=['created_at'], name='startup_ide_created_2ccf4c_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'slug'), name='unique_owner_slug')],
            },
        ),
    ]
