# Generated by Django 6.0.6 on 2026-06-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup_ideas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupidea',
            name='analysis_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startupidea',
            name='analysis_progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='startupidea',
            name='analysis_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startupidea',
            name='analysis_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('PARTIAL', 'Partial'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
