# Generated by Django 6.0.6 on 2026-06-27 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('startup_ideas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('total_sources', models.PositiveIntegerField(default=0)),
                ('processed_sources', models.PositiveIntegerField(default=0)),
                ('failed_sources', models.PositiveIntegerField(default=0)),
                ('duplicate_sources', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('startup_idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_jobs', to='startup_ideas.startupidea')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('original_url', models.URLField(max_length=2000)),
                ('canonical_url', models.URLField(max_length=2000)),
                ('domain', models.CharField(max_length=255)),
                ('provider', models.CharField(choices=[('GOOGLE', 'Google'), ('REDDIT', 'Reddit'), ('GITHUB', 'GitHub'), ('NEWS', 'News'), ('WEBSITE', 'Website')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('NORMALIZED', 'Normalized'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('excerpt', models.TextField()),
                ('author', models.CharField(blank=True, max_length=255)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('credibility_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('language', models.CharField(default='en', max_length=10)),
                ('content_hash', models.CharField(max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('research_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='research.researchjob')),
            ],
        ),
        migrations.AddIndex(
            model_name='researchjob',
            index=models.Index(fields=['startup_idea'], name='research_re_startup_b4d994_idx'),
        ),
        migrations.AddIndex(
            model_name='researchjob',
            index=models.Index(fields=['status'], name='research_re_status_4b9bb4_idx'),
        ),
        migrations.AddIndex(
            model_name='researchjob',
            index=models.Index(fields=['created_at'], name='research_re_created_b82384_idx'),
        ),
        migrations.AddIndex(
            model_name='researchsource',
            index=models.Index(fields=['research_job'], name='research_re_researc_ec1275_idx'),
        ),
        migrations.AddIndex(
            model_name='researchsource',
            index=models.Index(fields=['provider'], name='research_re_provide_6cbcc2_idx'),
        ),
        migrations.AddIndex(
            model_name='researchsource',
            index=models.Index(fields=['domain'], name='research_re_domain_948e06_idx'),
        ),
        migrations.AddIndex(
            model_name='researchsource',
            index=models.Index(fields=['published_at'], name='research_re_publish_7dac23_idx'),
        ),
        migrations.AddIndex(
            model_name='researchsource',
            index=models.Index(fields=['content_hash'], name='research_re_content_ee7417_idx'),
        ),
        migrations.AddConstraint(
            model_name='researchsource',
            constraint=models.UniqueConstraint(fields=('research_job', 'canonical_url'), name='unique_job_url'),
        ),
    ]
