# Generated by Django 6.0.6 on 2026-06-27 08:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('startup_ideas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('algorithm', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('feature_schema_version', models.CharField(max_length=50)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('artifact_path', models.CharField(help_text='Path to serialized model (e.g., .joblib or .pkl)', max_length=500)),
                ('is_active', models.BooleanField(default=False)),
                ('trained_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('predicted_success_probability', models.FloatField(help_text='Probability between 0.0 and 1.0')),
                ('predicted_failure_probability', models.FloatField(help_text='Probability between 0.0 and 1.0')),
                ('feature_importances', models.JSONField(blank=True, default=dict, help_text='Top contributing features for this specific prediction (SHAP values, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ml.predictionmodel')),
                ('startup_idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='startup_ideas.startupidea')),
            ],
        ),
        migrations.CreateModel(
            name='StartupFeatureVector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema_version', models.CharField(max_length=50)),
                ('features', models.JSONField(help_text='Dictionary of engineered features ready for inference')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('startup_idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_vectors', to='startup_ideas.startupidea')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dataset_path', models.CharField(max_length=500)),
                ('parameters', models.JSONField(help_text='Hyperparameters used for training')),
                ('metrics', models.JSONField(help_text='Full training metrics and confusion matrix')),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_runs', to='ml.predictionmodel')),
            ],
        ),
    ]
