# Generated by Django 6.0.6 on 2026-06-27 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment', '0001_initial'),
        ('startup_ideas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('market_percentage', 'Market Percentage'), ('competition_percentage', 'Competition Percentage'), ('demand_percentage', 'Demand Percentage'), ('business_model_percentage', 'Business Model Percentage'), ('revenue_percentage', 'Revenue Percentage'), ('technology_percentage', 'Technology Percentage'), ('execution_percentage', 'Execution Percentage'), ('scalability_percentage', 'Scalability Percentage'), ('risk_percentage', 'Risk Percentage'), ('overall_score', 'Overall Score')], max_length=50)),
                ('operator', models.CharField(choices=[('<', 'Less Than'), ('<=', 'Less Than or Equal'), ('>', 'Greater Than'), ('>=', 'Greater Than or Equal'), ('=', 'Equal'), ('BETWEEN', 'Between')], max_length=10)),
                ('minimum_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('maximum_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('priority', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('OPTIONAL', 'Optional')], max_length=20)),
                ('rule_group', models.CharField(choices=[('GROWTH', 'Growth'), ('FUNDING', 'Funding'), ('TECHNOLOGY', 'Technology'), ('COMPETITION', 'Competition'), ('EXECUTION', 'Execution'), ('RISK', 'Risk')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('recommended_action', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order'],
                'constraints': [models.UniqueConstraint(fields=('metric', 'operator', 'minimum_value', 'maximum_value', 'display_order'), name='unique_recommendation_rule')],
            },
        ),
        migrations.CreateModel(
            name='RecommendationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_priority', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('OPTIONAL', 'Optional')], max_length=20)),
                ('executive_summary', models.TextField()),
                ('total_recommendations', models.PositiveIntegerField(default=0)),
                ('critical_count', models.PositiveIntegerField(default=0)),
                ('high_count', models.PositiveIntegerField(default=0)),
                ('medium_count', models.PositiveIntegerField(default=0)),
                ('low_count', models.PositiveIntegerField(default=0)),
                ('optional_count', models.PositiveIntegerField(default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('overall_score_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('overall_grade_snapshot', models.CharField(blank=True, max_length=20, null=True)),
                ('assessment_version', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('overall_assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessment.overallassessment')),
                ('startup_idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_summaries', to='startup_ideas.startupidea')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('OPTIONAL', 'Optional')], max_length=20)),
                ('category', models.CharField(choices=[('MARKET', 'Market'), ('COMPETITION', 'Competition'), ('TECHNOLOGY', 'Technology'), ('FUNDING', 'Funding'), ('RISK', 'Risk'), ('EXECUTION', 'Execution'), ('OVERALL', 'Overall')], max_length=50)),
                ('status', models.CharField(choices=[('GENERATED', 'Generated'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('SUPERSEDED', 'Superseded'), ('ARCHIVED', 'Archived')], default='GENERATED', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('recommended_action', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_recommendations', to='assessment.assessment')),
                ('startup_idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='startup_ideas.startupidea')),
                ('matched_rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_recommendations', to='recommendations.recommendationrule')),
            ],
            options={
                'indexes': [models.Index(fields=['startup_idea'], name='recommendat_startup_9255c9_idx'), models.Index(fields=['status'], name='recommendat_status_d2897f_idx'), models.Index(fields=['priority'], name='recommendat_priorit_1f1dad_idx')],
                'constraints': [models.UniqueConstraint(fields=('startup_idea', 'matched_rule', 'version'), name='unique_startup_rule_version')],
            },
        ),
    ]
