# Generated by Django 6.0.6 on 2026-06-27 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge', '0001_initial'),
        ('research', '0001_initial'),
        ('startup_ideas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('COMPETITION', 'Competition'), ('MARKET', 'Market'), ('PRICING', 'Pricing'), ('DEMAND', 'Demand'), ('TARGET_AUDIENCE', 'Target Audience'), ('TECHNOLOGY', 'Technology'), ('FUNDING', 'Funding'), ('REGULATION', 'Regulation'), ('RISK', 'Risk'), ('OPPORTUNITY', 'Opportunity'), ('BUSINESS_MODEL', 'Business Model')], max_length=50)),
                ('status', models.CharField(choices=[('GENERATED', 'Generated'), ('VERIFIED', 'Verified'), ('STALE', 'Stale')], default='GENERATED', max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField()),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('version', models.PositiveIntegerField(default=1)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_from_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='research.researchjob')),
                ('startup_idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='startup_ideas.startupidea')),
                ('supporting_findings', models.ManyToManyField(related_name='supported_insights', to='knowledge.finding')),
            ],
            options={
                'indexes': [models.Index(fields=['startup_idea'], name='business_in_startup_aa8847_idx'), models.Index(fields=['generated_from_job'], name='business_in_generat_f01910_idx'), models.Index(fields=['insight_type'], name='business_in_insight_841212_idx'), models.Index(fields=['status'], name='business_in_status_e4947b_idx'), models.Index(fields=['confidence_score'], name='business_in_confide_a05586_idx'), models.Index(fields=['created_at'], name='business_in_created_9028b9_idx')],
                'constraints': [models.UniqueConstraint(fields=('startup_idea', 'insight_type', 'title', 'version'), name='unique_insight_version')],
            },
        ),
    ]
